// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Graph.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// dateTimeTimeZone
    /// </summary>
    public partial class MicrosoftgraphdateTimeTimeZone
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphdateTimeTimeZone
        /// class.
        /// </summary>
        public MicrosoftgraphdateTimeTimeZone()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphdateTimeTimeZone
        /// class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="dateTime">A single point of time in a combined date
        /// and time representation ({date}T{time}; for example,
        /// 2017-08-29T04:00:00.0000000).</param>
        /// <param name="timeZone">Represents a time zone, for example,
        /// 'Pacific Standard Time'. See below for more possible
        /// values.</param>
        public MicrosoftgraphdateTimeTimeZone(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string dateTime = default(string), string timeZone = default(string))
        {
            AdditionalProperties = additionalProperties;
            DateTime = dateTime;
            TimeZone = timeZone;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets a single point of time in a combined date and time
        /// representation ({date}T{time}; for example,
        /// 2017-08-29T04:00:00.0000000).
        /// </summary>
        [JsonProperty(PropertyName = "dateTime")]
        public string DateTime { get; set; }

        /// <summary>
        /// Gets or sets represents a time zone, for example, 'Pacific Standard
        /// Time'. See below for more possible values.
        /// </summary>
        [JsonProperty(PropertyName = "timeZone")]
        public string TimeZone { get; set; }

    }
}
