// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Graph.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// emailAddress
    /// </summary>
    public partial class MicrosoftgraphemailAddress
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphemailAddress class.
        /// </summary>
        public MicrosoftgraphemailAddress()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphemailAddress class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="address">The email address of the person or
        /// entity.</param>
        /// <param name="name">The display name of the person or
        /// entity.</param>
        public MicrosoftgraphemailAddress(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string address = default(string), string name = default(string))
        {
            AdditionalProperties = additionalProperties;
            Address = address;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets the email address of the person or entity.
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or sets the display name of the person or entity.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
