// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Graph.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// followupFlag
    /// </summary>
    public partial class MicrosoftgraphfollowupFlag
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphfollowupFlag class.
        /// </summary>
        public MicrosoftgraphfollowupFlag()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphfollowupFlag class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="flagStatus">Possible values include: 'notFlagged',
        /// 'complete', 'flagged'</param>
        public MicrosoftgraphfollowupFlag(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), MicrosoftgraphdateTimeTimeZone completedDateTime = default(MicrosoftgraphdateTimeTimeZone), MicrosoftgraphdateTimeTimeZone dueDateTime = default(MicrosoftgraphdateTimeTimeZone), string flagStatus = default(string), MicrosoftgraphdateTimeTimeZone startDateTime = default(MicrosoftgraphdateTimeTimeZone))
        {
            AdditionalProperties = additionalProperties;
            CompletedDateTime = completedDateTime;
            DueDateTime = dueDateTime;
            FlagStatus = flagStatus;
            StartDateTime = startDateTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "completedDateTime")]
        public MicrosoftgraphdateTimeTimeZone CompletedDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dueDateTime")]
        public MicrosoftgraphdateTimeTimeZone DueDateTime { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'notFlagged', 'complete',
        /// 'flagged'
        /// </summary>
        [JsonProperty(PropertyName = "flagStatus")]
        public string FlagStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startDateTime")]
        public MicrosoftgraphdateTimeTimeZone StartDateTime { get; set; }

    }
}
