// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Graph.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// inferenceClassification
    /// </summary>
    public partial class MicrosoftgraphinferenceClassification : Microsoftgraphentity
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphinferenceClassification class.
        /// </summary>
        public MicrosoftgraphinferenceClassification()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphinferenceClassification class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="id">Read-only.</param>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="overrides">A set of overrides for a user to always
        /// classify messages from specific senders in certain ways: focused,
        /// or other. Read-only. Nullable.</param>
        public MicrosoftgraphinferenceClassification(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string id = default(string), IList<MicrosoftgraphinferenceClassificationOverride> overrides = default(IList<MicrosoftgraphinferenceClassificationOverride>))
            : base(additionalProperties, id)
        {
            AdditionalProperties = additionalProperties;
            Overrides = overrides;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets a set of overrides for a user to always classify
        /// messages from specific senders in certain ways: focused, or other.
        /// Read-only. Nullable.
        /// </summary>
        [JsonProperty(PropertyName = "overrides")]
        public IList<MicrosoftgraphinferenceClassificationOverride> Overrides { get; set; }

    }
}
