// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Graph.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// internetMessageHeader
    /// </summary>
    public partial class MicrosoftgraphinternetMessageHeader
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphinternetMessageHeader class.
        /// </summary>
        public MicrosoftgraphinternetMessageHeader()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphinternetMessageHeader class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="name">Represents the key in a key-value pair.</param>
        /// <param name="value">The value in a key-value pair.</param>
        public MicrosoftgraphinternetMessageHeader(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string name = default(string), string value = default(string))
        {
            AdditionalProperties = additionalProperties;
            Name = name;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets represents the key in a key-value pair.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the value in a key-value pair.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
