// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Graph.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// messageRuleActions
    /// </summary>
    public partial class MicrosoftgraphmessageRuleActions
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphmessageRuleActions
        /// class.
        /// </summary>
        public MicrosoftgraphmessageRuleActions()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphmessageRuleActions
        /// class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="assignCategories">A list of categories to be assigned
        /// to a message.</param>
        /// <param name="copyToFolder">The ID of a folder that a message is to
        /// be copied to.</param>
        /// <param name="delete">Indicates whether a message should be moved to
        /// the Deleted Items folder.</param>
        /// <param name="forwardAsAttachmentTo">The email addresses of the
        /// recipients to which a message should be forwarded as an
        /// attachment.</param>
        /// <param name="forwardTo">The email addresses of the recipients to
        /// which a message should be forwarded.</param>
        /// <param name="markAsRead">Indicates whether a message should be
        /// marked as read.</param>
        /// <param name="markImportance">Possible values include: 'low',
        /// 'normal', 'high'</param>
        /// <param name="moveToFolder">The ID of the folder that a message will
        /// be moved to.</param>
        /// <param name="permanentDelete">Indicates whether a message should be
        /// permanently deleted and not saved to the Deleted Items
        /// folder.</param>
        /// <param name="redirectTo">The email addresses to which a message
        /// should be redirected.</param>
        /// <param name="stopProcessingRules">Indicates whether subsequent
        /// rules should be evaluated.</param>
        public MicrosoftgraphmessageRuleActions(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), IList<string> assignCategories = default(IList<string>), string copyToFolder = default(string), bool? delete = default(bool?), IList<Microsoftgraphrecipient> forwardAsAttachmentTo = default(IList<Microsoftgraphrecipient>), IList<Microsoftgraphrecipient> forwardTo = default(IList<Microsoftgraphrecipient>), bool? markAsRead = default(bool?), string markImportance = default(string), string moveToFolder = default(string), bool? permanentDelete = default(bool?), IList<Microsoftgraphrecipient> redirectTo = default(IList<Microsoftgraphrecipient>), bool? stopProcessingRules = default(bool?))
        {
            AdditionalProperties = additionalProperties;
            AssignCategories = assignCategories;
            CopyToFolder = copyToFolder;
            Delete = delete;
            ForwardAsAttachmentTo = forwardAsAttachmentTo;
            ForwardTo = forwardTo;
            MarkAsRead = markAsRead;
            MarkImportance = markImportance;
            MoveToFolder = moveToFolder;
            PermanentDelete = permanentDelete;
            RedirectTo = redirectTo;
            StopProcessingRules = stopProcessingRules;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets a list of categories to be assigned to a message.
        /// </summary>
        [JsonProperty(PropertyName = "assignCategories")]
        public IList<string> AssignCategories { get; set; }

        /// <summary>
        /// Gets or sets the ID of a folder that a message is to be copied to.
        /// </summary>
        [JsonProperty(PropertyName = "copyToFolder")]
        public string CopyToFolder { get; set; }

        /// <summary>
        /// Gets or sets indicates whether a message should be moved to the
        /// Deleted Items folder.
        /// </summary>
        [JsonProperty(PropertyName = "delete")]
        public bool? Delete { get; set; }

        /// <summary>
        /// Gets or sets the email addresses of the recipients to which a
        /// message should be forwarded as an attachment.
        /// </summary>
        [JsonProperty(PropertyName = "forwardAsAttachmentTo")]
        public IList<Microsoftgraphrecipient> ForwardAsAttachmentTo { get; set; }

        /// <summary>
        /// Gets or sets the email addresses of the recipients to which a
        /// message should be forwarded.
        /// </summary>
        [JsonProperty(PropertyName = "forwardTo")]
        public IList<Microsoftgraphrecipient> ForwardTo { get; set; }

        /// <summary>
        /// Gets or sets indicates whether a message should be marked as read.
        /// </summary>
        [JsonProperty(PropertyName = "markAsRead")]
        public bool? MarkAsRead { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'low', 'normal', 'high'
        /// </summary>
        [JsonProperty(PropertyName = "markImportance")]
        public string MarkImportance { get; set; }

        /// <summary>
        /// Gets or sets the ID of the folder that a message will be moved to.
        /// </summary>
        [JsonProperty(PropertyName = "moveToFolder")]
        public string MoveToFolder { get; set; }

        /// <summary>
        /// Gets or sets indicates whether a message should be permanently
        /// deleted and not saved to the Deleted Items folder.
        /// </summary>
        [JsonProperty(PropertyName = "permanentDelete")]
        public bool? PermanentDelete { get; set; }

        /// <summary>
        /// Gets or sets the email addresses to which a message should be
        /// redirected.
        /// </summary>
        [JsonProperty(PropertyName = "redirectTo")]
        public IList<Microsoftgraphrecipient> RedirectTo { get; set; }

        /// <summary>
        /// Gets or sets indicates whether subsequent rules should be
        /// evaluated.
        /// </summary>
        [JsonProperty(PropertyName = "stopProcessingRules")]
        public bool? StopProcessingRules { get; set; }

    }
}
