// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Graph.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// singleValueLegacyExtendedProperty
    /// </summary>
    public partial class MicrosoftgraphsingleValueLegacyExtendedProperty : Microsoftgraphentity
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphsingleValueLegacyExtendedProperty class.
        /// </summary>
        public MicrosoftgraphsingleValueLegacyExtendedProperty()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphsingleValueLegacyExtendedProperty class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="id">Read-only.</param>
        /// <param name="value">A property value.</param>
        public MicrosoftgraphsingleValueLegacyExtendedProperty(string id = default(string), IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string value = default(string))
            : base(additionalProperties, id)
        {
            // AdditionalProperties = additionalProperties;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        // [JsonExtensionData]
        // public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets a property value.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
