// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Graph.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// itemBody
    /// </summary>
    public partial class MicrosoftgraphitemBody
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphitemBody class.
        /// </summary>
        public MicrosoftgraphitemBody()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphitemBody class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="content">The content of the item.</param>
        /// <param name="contentType">Possible values include: 'text',
        /// 'html'</param>
        public MicrosoftgraphitemBody(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string content = default(string), string contentType = default(string))
        {
            AdditionalProperties = additionalProperties;
            Content = content;
            ContentType = contentType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets the content of the item.
        /// </summary>
        [JsonProperty(PropertyName = "content")]
        public string Content { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'text', 'html'
        /// </summary>
        [JsonProperty(PropertyName = "contentType")]
        public string ContentType { get; set; }

    }
}
