// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Graph
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface IMail : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Show only the first n items
        /// </summary>
        int? Top { get; set; }

        /// <summary>
        /// Skip the first n items
        /// </summary>
        int? Skip { get; set; }

        /// <summary>
        /// Search items by search phrases
        /// </summary>
        string Search { get; set; }

        /// <summary>
        /// Filter items by property values
        /// </summary>
        string Filter { get; set; }

        /// <summary>
        /// Include count of items
        /// </summary>
        bool? Count { get; set; }


        /// <summary>
        /// Gets the IUsers.
        /// </summary>
        IUsers Users { get; }

        /// <summary>
        /// Gets the IUsersinferenceClassification.
        /// </summary>
        IUsersinferenceClassification UsersinferenceClassification { get; }

        /// <summary>
        /// Gets the IUsersmailFolders.
        /// </summary>
        IUsersmailFolders UsersmailFolders { get; }

        /// <summary>
        /// Gets the IUsersmailFoldersmessages.
        /// </summary>
        IUsersmailFoldersmessages UsersmailFoldersmessages { get; }

        /// <summary>
        /// Gets the IUsersmessages.
        /// </summary>
        IUsersmessages Usersmessages { get; }

    }
}
