// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Graph
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Usersmessages.
    /// </summary>
    public static partial class UsersmessagesExtensions
    {
            /// <summary>
            /// Get attachments from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static Collectionofattachment0 ListAttachments(this IUsersmessages operations, string userId, string messageId, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.ListAttachmentsAsync(userId, messageId, orderby, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get attachments from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Collectionofattachment0> ListAttachmentsAsync(this IUsersmessages operations, string userId, string messageId, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ListAttachmentsWithHttpMessagesAsync(userId, messageId, orderby, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create new navigation property to attachments for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            public static Microsoftgraphattachment CreateAttachments(this IUsersmessages operations, Microsoftgraphattachment body, string userId, string messageId)
            {
                return operations.CreateAttachmentsAsync(body, userId, messageId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create new navigation property to attachments for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Microsoftgraphattachment> CreateAttachmentsAsync(this IUsersmessages operations, Microsoftgraphattachment body, string userId, string messageId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateAttachmentsWithHttpMessagesAsync(body, userId, messageId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get attachments from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='attachmentId'>
            /// key: id of attachment
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static Microsoftgraphattachment GetAttachments(this IUsersmessages operations, string userId, string messageId, string attachmentId, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.GetAttachmentsAsync(userId, messageId, attachmentId, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get attachments from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='attachmentId'>
            /// key: id of attachment
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Microsoftgraphattachment> GetAttachmentsAsync(this IUsersmessages operations, string userId, string messageId, string attachmentId, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAttachmentsWithHttpMessagesAsync(userId, messageId, attachmentId, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Update the navigation property attachments in users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property values
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='attachmentId'>
            /// key: id of attachment
            /// </param>
            public static void UpdateAttachments(this IUsersmessages operations, Microsoftgraphattachment body, string userId, string messageId, string attachmentId)
            {
                operations.UpdateAttachmentsAsync(body, userId, messageId, attachmentId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update the navigation property attachments in users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property values
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='attachmentId'>
            /// key: id of attachment
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task UpdateAttachmentsAsync(this IUsersmessages operations, Microsoftgraphattachment body, string userId, string messageId, string attachmentId, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.UpdateAttachmentsWithHttpMessagesAsync(body, userId, messageId, attachmentId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Delete navigation property attachments for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='attachmentId'>
            /// key: id of attachment
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            public static void DeleteAttachments(this IUsersmessages operations, string userId, string messageId, string attachmentId, string ifMatch = default(string))
            {
                operations.DeleteAttachmentsAsync(userId, messageId, attachmentId, ifMatch).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete navigation property attachments for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='attachmentId'>
            /// key: id of attachment
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteAttachmentsAsync(this IUsersmessages operations, string userId, string messageId, string attachmentId, string ifMatch = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteAttachmentsWithHttpMessagesAsync(userId, messageId, attachmentId, ifMatch, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Get extensions from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static Collectionofextension0 ListExtensions(this IUsersmessages operations, string userId, string messageId, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.ListExtensionsAsync(userId, messageId, orderby, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get extensions from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Collectionofextension0> ListExtensionsAsync(this IUsersmessages operations, string userId, string messageId, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ListExtensionsWithHttpMessagesAsync(userId, messageId, orderby, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create new navigation property to extensions for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            public static IDictionary<string, object> CreateExtensions(this IUsersmessages operations, IDictionary<string, object> body, string userId, string messageId)
            {
                return operations.CreateExtensionsAsync(body, userId, messageId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create new navigation property to extensions for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IDictionary<string, object>> CreateExtensionsAsync(this IUsersmessages operations, IDictionary<string, object> body, string userId, string messageId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateExtensionsWithHttpMessagesAsync(body, userId, messageId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get extensions from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='extensionId'>
            /// key: id of extension
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static IDictionary<string, object> GetExtensions(this IUsersmessages operations, string userId, string messageId, string extensionId, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.GetExtensionsAsync(userId, messageId, extensionId, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get extensions from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='extensionId'>
            /// key: id of extension
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IDictionary<string, object>> GetExtensionsAsync(this IUsersmessages operations, string userId, string messageId, string extensionId, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetExtensionsWithHttpMessagesAsync(userId, messageId, extensionId, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Update the navigation property extensions in users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property values
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='extensionId'>
            /// key: id of extension
            /// </param>
            public static void UpdateExtensions(this IUsersmessages operations, IDictionary<string, object> body, string userId, string messageId, string extensionId)
            {
                operations.UpdateExtensionsAsync(body, userId, messageId, extensionId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update the navigation property extensions in users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property values
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='extensionId'>
            /// key: id of extension
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task UpdateExtensionsAsync(this IUsersmessages operations, IDictionary<string, object> body, string userId, string messageId, string extensionId, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.UpdateExtensionsWithHttpMessagesAsync(body, userId, messageId, extensionId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Delete navigation property extensions for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='extensionId'>
            /// key: id of extension
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            public static void DeleteExtensions(this IUsersmessages operations, string userId, string messageId, string extensionId, string ifMatch = default(string))
            {
                operations.DeleteExtensionsAsync(userId, messageId, extensionId, ifMatch).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete navigation property extensions for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='extensionId'>
            /// key: id of extension
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteExtensionsAsync(this IUsersmessages operations, string userId, string messageId, string extensionId, string ifMatch = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteExtensionsWithHttpMessagesAsync(userId, messageId, extensionId, ifMatch, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Get multiValueExtendedProperties from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static CollectionofmultiValueLegacyExtendedProperty1 ListMultiValueExtendedProperties(this IUsersmessages operations, string userId, string messageId, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.ListMultiValueExtendedPropertiesAsync(userId, messageId, orderby, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get multiValueExtendedProperties from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CollectionofmultiValueLegacyExtendedProperty1> ListMultiValueExtendedPropertiesAsync(this IUsersmessages operations, string userId, string messageId, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ListMultiValueExtendedPropertiesWithHttpMessagesAsync(userId, messageId, orderby, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create new navigation property to multiValueExtendedProperties for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            public static MicrosoftgraphmultiValueLegacyExtendedProperty CreateMultiValueExtendedProperties(this IUsersmessages operations, MicrosoftgraphmultiValueLegacyExtendedProperty body, string userId, string messageId)
            {
                return operations.CreateMultiValueExtendedPropertiesAsync(body, userId, messageId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create new navigation property to multiValueExtendedProperties for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftgraphmultiValueLegacyExtendedProperty> CreateMultiValueExtendedPropertiesAsync(this IUsersmessages operations, MicrosoftgraphmultiValueLegacyExtendedProperty body, string userId, string messageId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateMultiValueExtendedPropertiesWithHttpMessagesAsync(body, userId, messageId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get multiValueExtendedProperties from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='multiValueLegacyExtendedPropertyId'>
            /// key: id of multiValueLegacyExtendedProperty
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static MicrosoftgraphmultiValueLegacyExtendedProperty GetMultiValueExtendedProperties(this IUsersmessages operations, string userId, string messageId, string multiValueLegacyExtendedPropertyId, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.GetMultiValueExtendedPropertiesAsync(userId, messageId, multiValueLegacyExtendedPropertyId, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get multiValueExtendedProperties from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='multiValueLegacyExtendedPropertyId'>
            /// key: id of multiValueLegacyExtendedProperty
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftgraphmultiValueLegacyExtendedProperty> GetMultiValueExtendedPropertiesAsync(this IUsersmessages operations, string userId, string messageId, string multiValueLegacyExtendedPropertyId, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetMultiValueExtendedPropertiesWithHttpMessagesAsync(userId, messageId, multiValueLegacyExtendedPropertyId, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Update the navigation property multiValueExtendedProperties in users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property values
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='multiValueLegacyExtendedPropertyId'>
            /// key: id of multiValueLegacyExtendedProperty
            /// </param>
            public static void UpdateMultiValueExtendedProperties(this IUsersmessages operations, MicrosoftgraphmultiValueLegacyExtendedProperty body, string userId, string messageId, string multiValueLegacyExtendedPropertyId)
            {
                operations.UpdateMultiValueExtendedPropertiesAsync(body, userId, messageId, multiValueLegacyExtendedPropertyId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update the navigation property multiValueExtendedProperties in users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property values
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='multiValueLegacyExtendedPropertyId'>
            /// key: id of multiValueLegacyExtendedProperty
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task UpdateMultiValueExtendedPropertiesAsync(this IUsersmessages operations, MicrosoftgraphmultiValueLegacyExtendedProperty body, string userId, string messageId, string multiValueLegacyExtendedPropertyId, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.UpdateMultiValueExtendedPropertiesWithHttpMessagesAsync(body, userId, messageId, multiValueLegacyExtendedPropertyId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Delete navigation property multiValueExtendedProperties for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='multiValueLegacyExtendedPropertyId'>
            /// key: id of multiValueLegacyExtendedProperty
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            public static void DeleteMultiValueExtendedProperties(this IUsersmessages operations, string userId, string messageId, string multiValueLegacyExtendedPropertyId, string ifMatch = default(string))
            {
                operations.DeleteMultiValueExtendedPropertiesAsync(userId, messageId, multiValueLegacyExtendedPropertyId, ifMatch).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete navigation property multiValueExtendedProperties for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='multiValueLegacyExtendedPropertyId'>
            /// key: id of multiValueLegacyExtendedProperty
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteMultiValueExtendedPropertiesAsync(this IUsersmessages operations, string userId, string messageId, string multiValueLegacyExtendedPropertyId, string ifMatch = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteMultiValueExtendedPropertiesWithHttpMessagesAsync(userId, messageId, multiValueLegacyExtendedPropertyId, ifMatch, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Get singleValueExtendedProperties from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static CollectionofsingleValueLegacyExtendedProperty1 ListSingleValueExtendedProperties(this IUsersmessages operations, string userId, string messageId, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.ListSingleValueExtendedPropertiesAsync(userId, messageId, orderby, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get singleValueExtendedProperties from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CollectionofsingleValueLegacyExtendedProperty1> ListSingleValueExtendedPropertiesAsync(this IUsersmessages operations, string userId, string messageId, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ListSingleValueExtendedPropertiesWithHttpMessagesAsync(userId, messageId, orderby, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create new navigation property to singleValueExtendedProperties for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            public static MicrosoftgraphsingleValueLegacyExtendedProperty CreateSingleValueExtendedProperties(this IUsersmessages operations, MicrosoftgraphsingleValueLegacyExtendedProperty body, string userId, string messageId)
            {
                return operations.CreateSingleValueExtendedPropertiesAsync(body, userId, messageId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create new navigation property to singleValueExtendedProperties for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftgraphsingleValueLegacyExtendedProperty> CreateSingleValueExtendedPropertiesAsync(this IUsersmessages operations, MicrosoftgraphsingleValueLegacyExtendedProperty body, string userId, string messageId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateSingleValueExtendedPropertiesWithHttpMessagesAsync(body, userId, messageId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get singleValueExtendedProperties from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='singleValueLegacyExtendedPropertyId'>
            /// key: id of singleValueLegacyExtendedProperty
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static MicrosoftgraphsingleValueLegacyExtendedProperty GetSingleValueExtendedProperties(this IUsersmessages operations, string userId, string messageId, string singleValueLegacyExtendedPropertyId, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.GetSingleValueExtendedPropertiesAsync(userId, messageId, singleValueLegacyExtendedPropertyId, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get singleValueExtendedProperties from users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='singleValueLegacyExtendedPropertyId'>
            /// key: id of singleValueLegacyExtendedProperty
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftgraphsingleValueLegacyExtendedProperty> GetSingleValueExtendedPropertiesAsync(this IUsersmessages operations, string userId, string messageId, string singleValueLegacyExtendedPropertyId, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSingleValueExtendedPropertiesWithHttpMessagesAsync(userId, messageId, singleValueLegacyExtendedPropertyId, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Update the navigation property singleValueExtendedProperties in users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property values
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='singleValueLegacyExtendedPropertyId'>
            /// key: id of singleValueLegacyExtendedProperty
            /// </param>
            public static void UpdateSingleValueExtendedProperties(this IUsersmessages operations, MicrosoftgraphsingleValueLegacyExtendedProperty body, string userId, string messageId, string singleValueLegacyExtendedPropertyId)
            {
                operations.UpdateSingleValueExtendedPropertiesAsync(body, userId, messageId, singleValueLegacyExtendedPropertyId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update the navigation property singleValueExtendedProperties in users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New navigation property values
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='singleValueLegacyExtendedPropertyId'>
            /// key: id of singleValueLegacyExtendedProperty
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task UpdateSingleValueExtendedPropertiesAsync(this IUsersmessages operations, MicrosoftgraphsingleValueLegacyExtendedProperty body, string userId, string messageId, string singleValueLegacyExtendedPropertyId, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.UpdateSingleValueExtendedPropertiesWithHttpMessagesAsync(body, userId, messageId, singleValueLegacyExtendedPropertyId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Delete navigation property singleValueExtendedProperties for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='singleValueLegacyExtendedPropertyId'>
            /// key: id of singleValueLegacyExtendedProperty
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            public static void DeleteSingleValueExtendedProperties(this IUsersmessages operations, string userId, string messageId, string singleValueLegacyExtendedPropertyId, string ifMatch = default(string))
            {
                operations.DeleteSingleValueExtendedPropertiesAsync(userId, messageId, singleValueLegacyExtendedPropertyId, ifMatch).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete navigation property singleValueExtendedProperties for users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// key: id of user
            /// </param>
            /// <param name='messageId'>
            /// key: id of message
            /// </param>
            /// <param name='singleValueLegacyExtendedPropertyId'>
            /// key: id of singleValueLegacyExtendedProperty
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteSingleValueExtendedPropertiesAsync(this IUsersmessages operations, string userId, string messageId, string singleValueLegacyExtendedPropertyId, string ifMatch = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteSingleValueExtendedPropertiesWithHttpMessagesAsync(userId, messageId, singleValueLegacyExtendedPropertyId, ifMatch, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
